config/routes.rb
    namespace :post do
      resources :posts, :only => [:delete, :expunge, :confirm_delete] do
        member do
          post :expunge
          get :confirm_move_favorites
          post :move_favorites
          post :ban
          post :unban
        end
      end
    end
  end
  namespace :explore do
    resources :posts, :only => [] do
      collection do
        get :popular
        get :curated
        get :viewed
        get :searches
        get :missed_searches
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, only: [:show, :create, :destroy]
    end
  end

  resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]

  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
    end
    collection do
      get :show_or_new
      get :banned
    end
  end
  resources :artist_urls, only: [:index]
  resources :artist_versions, :only => [:index, :show] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comment_votes, only: [:index, :show, :destroy]
  resources :comments do
    resource :votes, controller: "comment_votes", only: [:create, :destroy], as: "comment_votes" do
      get "/", action: :index
    end
    collection do
      get :search, to: redirect("/comments?group_by=comment")
    end
    member do
      post :undelete
    end
  end
  resources :counts do
    collection do
      get :posts
    end
  end
  resources :jobs, only: [:index, :destroy] do
    member do
      put :run
      put :retry
      put :cancel
    end
  end
  resources :dmails, :only => [:new, :create, :update, :index, :show] do
    collection do
      post :mark_all_as_read
    end
  end
  resource  :dtext_preview, :only => [:create]
  resources :dtext_links, only: [:index]
  resources :emails, only: [:index, :show]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :favorite_groups do
    member do
      put :add_post
      put :remove_post
    end
    resource :order, :only => [:edit], :controller => "favorite_group_orders"
  end
  resources :forum_posts do
    member do
      post :undelete
    end
    collection do
      get :search
    end
  end
  resources :forum_post_votes, only: [:index, :show, :create, :destroy]
  resources :forum_topics do
    member do
      post :undelete
    end
    collection do
      post :mark_all_as_read
    end
  end
  resources :forum_topic_visits, only: [:index]
  resources :ip_bans, only: [:index, :show, :new, :create, :update]
  resources :ip_addresses, only: [:show], id: /.+?(?=\.json|\.xml|\.html)|.+/
  resources :ip_geolocations, only: [:index]
  resource :iqdb_queries, :only => [:show, :create] do
    collection do
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :media_assets, only: [:index, :show] do
    get "/:variant", to: "media_assets#image", as: :image
  end
  resources :media_metadata, only: [:index]

  resources :ai_tags, only: [:index]
  put "/ai_tags/:media_asset_id/:tag_id/tag", to: "ai_tags#tag", as: "tag_ai_tag"

  resources :mod_actions
  resources :moderation_reports, only: [:new, :create, :index, :show, :update]
  resources :modqueue, only: [:index]
  resources :news_updates
  resources :notes do
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index, :show]
  resource :note_previews, only: [:create, :show]
  resource :password_reset, only: [:create, :show]
  resources :pools do
    member do
      put :revert
      post :undelete
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create]
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
    collection do
      get :search
    end
  end
  resources :post_events, only: [:index]
  resources :post_regenerations, :only => [:create]
  resources :post_replacements, only: [:index, :show, :new, :create, :update]
  resources :post_votes, only: [:index, :show, :create, :destroy]

  # XXX Use `only: []` to avoid redefining post routes defined at top of file.
  resources :posts, only: [] do
    resources :events, only: [:index], controller: "post_events", as: "post_events"
    resources :favorites, only: [:index, :create, :destroy]
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :artist_commentary, only: [:show] do
      collection { put :create_or_update }
      member { put :revert }
    end
    resource :votes, controller: "post_votes", only: [:create, :destroy], as: "post_votes"
    member do
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_appeals
  resources :post_flags
  resources :post_approvals, only: [:create, :index, :show]
  resources :post_disapprovals
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries, :only => [:index, :show] do
    collection do
      put :create_or_update
    end
    member do
      put :revert
    end
  end
  resources :artist_commentary_versions, :only => [:index, :show]
  resources :rate_limits, only: [:index]
  resource :related_tag, :only => [:show, :update]
  resources :recommended_posts, only: [:index]
  resources :reports, only: [:index, :show]
  resources :robots, only: [:index]
  resources :saved_searches, :except => [:show]
  resource :session, only: [:new, :create, :destroy] do
    get :confirm_password, on: :collection
    get :sign_out, on: :collection
  end
  resource :source, :only => [:show]
  resource :status, only: [:show], controller: "status"
  resources :tags
  resources :tag_aliases, only: [:show, :index, :destroy]
  resources :tag_implications, only: [:show, :index, :destroy]
  resources :tag_versions, only: [:index, :show]

  get "/redeem", to: "upgrade_codes#redeem", as: "redeem_upgrade_codes"
  resources :upgrade_codes, only: [:create, :index] do
    get :redeem, on: :collection
    post :upgrade, on: :collection
  end

  resources :uploads do
    collection do
      get :batch, to: redirect(path: "/uploads/new")
    end
    resources :upload_media_assets, only: [:show, :index], path: "assets"
  end
  resources :upload_media_assets, only: [:show, :index]
  resources :user_actions, only: [:index, :show]
  resources :users do
    resources :actions, only: [:index]
    resources :favorites, only: [:index, :create, :destroy]
    resources :favorite_groups, controller: "favorite_groups", only: [:index], as: "favorite_groups"
    resource :email, only: [:show, :edit, :update] do
      get :verify
      post :send_confirmation
    end
    resource :password, only: [:edit, :update]
    resources :api_keys, only: [:new, :create, :edit, :update, :index, :destroy]
    resources :uploads, only: [:index]

    get :change_name, on: :member, to: "user_name_change_requests#new"
    get :custom_style, on: :collection
    get :deactivate, on: :member     # /users/:id/deactivate
    get :deactivate, on: :collection # /users/deactivate
  end
  get "/upgrade", to: "user_upgrades#new", as: "new_user_upgrade"
  get "/user_upgrades/new", to: redirect("/upgrade")
  resources :user_upgrades, only: [:new, :create, :show, :index] do
    get :receipt, on: :member
    get :payment, on: :member
    put :refund, on: :member
  end
  resources :user_events, only: [:index]
  resources :user_feedbacks, except: [:destroy]
  resources :user_sessions, only: [:index]
  resources :user_name_change_requests, only: [:new, :create, :show, :index]
  resources :webhooks do
    post :receive, on: :collection
    post :authorize_net, on: :collection
  end
  resources :wiki_pages, id: /.+?(?=\.json|\.xml|\.html)|.+/ do
    put :revert, on: :member
    get :show_or_new, on: :collection
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resource :dmca, only: [:create, :show] do
    get :template
  end

  # Legacy Danbooru 1 API endpoints
  get "/tag/index.xml", :controller => "legacy", :action => "tags", :format => "xml"
  get "/tag/index.json", :controller => "legacy", :action => "tags", :format => "json"
  get "/post/index.xml", :controller => "legacy", :action => "posts", :format => "xml"
  get "/post/index.json", :controller => "legacy", :action => "posts", :format => "json"

  # Legacy Danbooru 1 redirects.
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI.escape(req.params[:name].to_s)}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")
  get "/artist/show" => redirect {|params, req| "/artists?name=#{CGI.escape(req.params[:name].to_s)}"}

  get "/forum" => redirect {|params, req| "/forum_topics?page=#{req.params[:page]}"}
  get "/forum/show/:id" => redirect {|params, req| "/forum_posts/#{req.params[:id]}?page=#{req.params[:page]}"}

  get "/pool/show/:id" => redirect("/pools/%{id}")

  get "/post/index" => redirect {|params, req| "/posts?tags=#{CGI.escape(req.params[:tags].to_s)}&page=#{req.params[:page]}"}
  get "/post/atom" => redirect {|params, req| "/posts.atom?tags=#{CGI.escape(req.params[:tags].to_s)}"}
  get "/post/show/:id/:tag_title" => redirect("/posts/%{id}")
  get "/post/show/:id" => redirect("/posts/%{id}")

  get "/tag" => redirect {|params, req| "/tags?page=#{req.params[:page]}&search[name_matches]=#{CGI.escape(req.params[:name].to_s)}&search[order]=#{req.params[:order]}&search[category]=#{req.params[:type]}"}

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  respond_to :html, :json, :xml

  rate_limit :show, rate: 1.0/3.seconds, burst: 15

  def index
  end

  def show
    @report = params[:id]
    @mode = params.dig(:search, :mode) || "chart"
    @period = params.dig(:search, :period)&.downcase
    @from = params.dig(:search, :from) || 1.month.ago
    @to = params.dig(:search, :to) || Time.zone.now
    @columns = params.dig(:search, :columns).to_s.split(/[[:space:],]/).map(&:to_sym)
    @group = params.dig(:search, :group)&.downcase&.tr(" ", "_")
    @group_limit = params.dig(:search, :group_limit)&.to_i || 10

    case @report
    when "posts"
      @model = Post
      @title = "Posts Report"
      @available_columns = { posts: "COUNT(*)", uploaders: "COUNT(distinct uploader_id)" }
      @available_groups = %w[uploader approver rating is_deleted]
    when "post_approvals"
      @model = PostApproval
      @title = "Post Approvals Report"
      @available_columns = { approvals: "COUNT(*)", approvers: "COUNT(distinct user_id)" }
      @available_groups = %w[user]
    when "post_appeals"
      @model = PostAppeal
      @title = "Post Appeals Report"
      @available_columns = { appeals: "COUNT(*)", appealers: "COUNT(distinct creator_id)" }
      @available_groups = %w[creator status]
    when "post_flags"
      @model = PostFlag
      @title = "Post Flags Report"
      @available_columns = { flags: "COUNT(*)", flaggers: "COUNT(distinct creator_id)" }
      @available_groups = %w[status]
    when "post_replacements"
      @model = PostReplacement
      @title = "Post Replacements Report"
      @available_columns = { replacements: "COUNT(*)", replacers: "COUNT(distinct creator_id)" }
      @available_groups = %w[creator]
    when "post_votes"
      @model = PostVote
      @title = "Post Votes Report"
      @available_columns = { votes: "COUNT(*)", posts: "COUNT(distinct post_id)", voters: "COUNT(distinct user_id)" }
      @available_groups = %w[]
    when "media_assets"
      @model = MediaAsset
      @title = "Media Assets Report"
      @available_columns = { assets: "COUNT(*)", size: "SUM(file_size)", duration: "SUM(duration)" }
      @available_groups = %w[file_ext status]
    when "pools"
      @model = Pool
      @title = "Pools Report"
      @available_columns = { pools: "COUNT(*)" }
      @available_groups = %w[category is_deleted]
    when "comments"
      @model = Comment
      @title = "Comments Report"
      @available_columns = { comments: "COUNT(*)", commenters: "COUNT(distinct creator_id)" }
      @available_groups = %w[creator do_not_bump_post is_deleted is_sticky]
    when "comment_votes"
      @model = CommentVote
      @title = "Comment Votes Report"
      @available_columns = { votes: "COUNT(*)", comments: "COUNT(distinct comment_id)", voters: "COUNT(distinct user_id)" }
      @available_groups = %w[]
    when "forum_posts"
      @model = ForumPost
      @title = "Forum Posts Report"
      @available_columns = { forum_posts: "COUNT(*)", posters: "COUNT(distinct creator_id)" }
      @available_groups = %w[creator is_deleted]
    when "bulk_update_requests"
      @model = BulkUpdateRequest
      @title = "Bulk Update Requests Report"
      @available_columns = { requests: "COUNT(*)", requestors: "COUNT(distinct user_id)" }
      @available_groups = %w[user approver status]
    when "tag_aliases"
      @model = TagAlias
      @title = "Tag Aliases Report"
      @available_columns = { aliases: "COUNT(*)" }
      @available_groups = %w[status approver]
    when "tag_implications"
      @model = TagImplication
      @title = "Tag Implications Report"
      @available_columns = { aliases: "COUNT(*)" }
      @available_groups = %w[status approver]
    when "artist_versions"
      @model = ArtistVersion
      @title = "Artist Edits Report"
      @available_columns = { artist_edits: "COUNT(*)", artists: "COUNT(distinct artist_id)", editors: "COUNT(distinct updater_id)" }
      @available_groups = %w[updater]
    when "artist_commentary_versions"
      @model = ArtistCommentaryVersion
      @title = "Artist Commentary Edits Report"
      @available_columns = { commentary_edits: "COUNT(*)", editors: "COUNT(distinct updater_id)" }
      @available_groups = %w[updater]
    when "note_versions"
      @model = NoteVersion
      @title = "Note Edits Report"
      @available_columns = { note_edits: "COUNT(*)", posts: "COUNT(distinct post_id)", editors: "COUNT(distinct updater_id)" }
      @available_groups = %w[updater]
    when "wiki_page_versions"
      @model = WikiPageVersion
      @title = "Wiki Edits Report"
      @available_columns = { wiki_edits: "COUNT(*)", editors: "COUNT(distinct updater_id)" }
      @available_groups = %w[updater]
    when "mod_actions"
      @model = ModAction
      @title = "Mod Actions Report"
      @available_columns = { mod_actions: "COUNT(*)", creators: "COUNT(distinct creator_id)" }
      @available_groups = %w[creator category subject_type]
    when "bans"
      @model = Ban
      @title = "Bans Report"
      @available_columns = { bans: "COUNT(*)", banners: "COUNT(DISTINCT banner_id)" }
      @available_groups = %w[banner duration]
    when "users"
      @model = User
      @title = "New Users Report"
      @available_columns = { users: "COUNT(*)" }
      @available_groups = %w[level]
    else
      raise ActiveRecord::RecordNotFound
    end

    if CurrentUser.user.is_member? && CurrentUser.user.statement_timeout < 10_000
      @statement_timeout = 10_000
    else
      @statement_timeout = CurrentUser.user.statement_timeout
    end

    ApplicationRecord.set_timeout(@statement_timeout) do
      @group = nil unless @group&.in?(@available_groups)
      @columns = @available_columns.slice(*@columns)
      @columns = [@available_columns.first].to_h if @columns.blank?

      if @period.present?
        @dataframe = @model.search(params[:search], CurrentUser.user).timeseries(period: @period, from: @from, to: @to, groups: [@group].compact_blank, group_limit: @group_limit, columns: @columns)
        @x_axis = "date"
      else
        @dataframe = @model.search(params[:search], CurrentUser.user).aggregate(from: @from, to: @to, groups: [@group].compact_blank, limit: @group_limit, columns: @columns)
        @x_axis = @group
      end

      @dataframe[@group] = @dataframe[@group].map(&:pretty_name) if @group.in?(%w[creator updater uploader banner approver user]) && @dataframe.names.include?(@group)
      @dataframe["date"] = @dataframe["date"].map(&:to_date) if @dataframe["date"]
      @dataframe = @dataframe.crosstab("date", @group) if @group && @period.present?
    end

    respond_with(@dataframe)
  end
end

app/views/reports/_tag_diff_list.html.erb
<span class="diff-list">
  <% added_tags.each do |tag| %>
    <ins>+<%= link_to wordbreakify(tag), posts_path(tags: tag) %></ins>
  <% end %>

  <% removed_tags.each do |tag| %>
    <del>-<%= link_to wordbreakify(tag), posts_path(tags: tag) %></del>
  <% end %>
</span>

app/views/reports/index.html.erb
<% page_title "Reports" %>

<div id="c-reports">
  <div id="a-index">
    <h1>Reports</h1>

    <ul class="list-bulleted">
      <li><%= link_to "Posts", report_path("posts", search: { period: "day" }) %></li>
      <li><%= link_to "Post approvals", report_path("post_approvals", search: { period: "day" }) %></li>
      <li><%= link_to "Post appeals", report_path("post_appeals", search: { period: "day" }) %></li>
      <li><%= link_to "Post flags", report_path("post_flags", search: { period: "day" }) %></li>
      <li><%= link_to "Post replacements", report_path("post_replacements", search: { period: "day" }) %></li>
      <li><%= link_to "Post votes", report_path("post_votes", search: { period: "day" }) %></li>
      <li><%= link_to "Media assets", report_path("media_assets", search: { period: "day" }) %></li>
      <li><%= link_to "Pools", report_path("pools", search: { period: "day" }) %></li>
      <li><%= link_to "Comments", report_path("comments", search: { period: "day" }) %></li>
      <li><%= link_to "Comment votes", report_path("comment_votes", search: { period: "day" }) %></li>
      <li><%= link_to "Forum posts", report_path("forum_posts", search: { period: "day" }) %></li>
      <li><%= link_to "Bulk update requests", report_path("bulk_update_requests", search: { period: "day" }) %></li>
      <li><%= link_to "Tag aliases", report_path("tag_aliases", search: { period: "day" }) %></li>
      <li><%= link_to "Tag implications", report_path("tag_implications", search: { period: "day" }) %></li>
      <li><%= link_to "Artist edits", report_path("artist_versions", search: { period: "day" }) %></li>
      <li><%= link_to "Artist commentary edits", report_path("artist_commentary_versions", search: { period: "day" }) %></li>
      <li><%= link_to "Note edits", report_path("note_versions", search: { period: "day" }) %></li>
      <li><%= link_to "Wiki edits", report_path("wiki_page_versions", search: { period: "day" }) %></li>
      <li><%= link_to "Mod actions", report_path("mod_actions", search: { period: "day" }) %></li>
      <li><%= link_to "Bans", report_path("bans", search: { period: "day" }) %></li>
      <li><%= link_to "Users", report_path("users", search: { period: "day" }) %></li>
    </ul>
  </div>
</div>

app/views/reports/show.html.erb
<% page_title @title %>

<div id="c-reports">
  <div id="a-show">
    <h1><%= @title %></h1>
    <%= link_to "« Back", reports_path, class: "text-xs" %>

    <%= search_form_for(current_page_path) do |f| %>
      <% if @report == "posts" %>
        <%= f.input :tags, label: "Tags", input_html: { value: params[:search][:tags], data: { autocomplete: "tag-query" } } %>
      <% end %>

      <%= f.input :from, as: :date, html5: true, input_html: { value: params[:search][:from] || 1.month.ago.to_date } %>
      <%= f.input :to, as: :date, html5: true, input_html: { value: params[:search][:to] || Time.zone.now.to_date } %>
      <%= f.input :period, collection: %w[day week month year].map { [_1.capitalize, _1] }, include_blank: true, selected: @period %>
      <%= f.input :group, label: "Group By", collection: @available_groups.map { |group| [group.titleize, group] }, include_blank: true, selected: params[:search][:group] if @available_groups.present? %>
      <%= f.input :group_limit, label: "Top", collection: [10, 25, 50, 100], selected: @group_limit if @group %>
      <%= f.input :mode, as: :hidden, input_html: { value: params[:search][:mode] } %>
      <%= f.submit "Search" %>
    <% end %>

    <%= render TimeSeriesComponent.new(@dataframe, x_axis: @x_axis, mode: @mode) %>
  </div>
</div>

app/views/reports/upload_tags.html.erb
<% page_title "Upload Tags: #{@user.pretty_name}" %>

<div id="c-reports">
  <div id="a-upload-tags">
    <h1>Upload tag changes report for <%= @user.pretty_name %></h1>

    <%= render "posts/partials/common/inline_blacklist" %>

    <%= table_for @upload_reports do |t| %>
      <% t.column "Post ID", width: "10%" do |upload_report| %>
        <%= post_preview(upload_report.becomes(Post), show_deleted: true, tags: "user:#{upload_report.uploader.name}") %>
      <% end %>
      <% t.column "Tags added by uploader", width: "45%" do |upload_report| %>
        <%= render_inline_tag_list(upload_report.uploader_tags_array) %>
      <% end %>
      <% t.column "Tags changed by other users", width: "45%" do |upload_report| %>
        <%= render "reports/tag_diff_list", added_tags: upload_report.added_tags_array, removed_tags: upload_report.removed_tags_array %>
      <% end %>
    <% end %>

    <%= numbered_paginator(@upload_reports) %>
    </div>
</div>